services:
  ssb:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "8000:8000"
    networks:
      - solary-system

  nginx:
    image: nginx:latest
    container_name: ss-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/nginx/default.conf:/etc/nginx/conf.d/client.conf 
      - ./client:/usr/share/nginx/html
    networks:
      - solary-system

networks:
  solary-system:
    driver: bridge