services:
  ssb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssb
    ports:
      - "8000:8000"
    networks:
      - solary-system

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - ssb
  #   networks:
  #     - solary-system
  #   expose:
  #     - 80

networks:
  solary-system:
    driver: bridge